spring:
  application:
    name: user-service

  profiles:
    active: localhost

server:
  port: 5865

---

spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://config-server:5859

eureka:
  instance:
    hostname: user-service
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

jwt:
  issuer_uri: http://keycloak:8080/realms/java-microservice-realm/protocol/openid-connect/token
  client_id: spring-cloud-client
  client_secret: AJufwN1eof8P5Gga5Y9atCFqdMuZEuKd
  grant_type: client_credentials
  scope: openid offline_access